import mongoose, { Schema, Document } from 'mongoose';
import randomatic from 'randomatic';

// Define the interface for the request document
export interface Request extends Document {
  userType: string;
  fullName: string;
  phoneNumber: string;
  emailAddress: string;
  homeAddress: string;
  medicalCondition?: string;
  milkAmount?: string;
  BabyCategory: string;
  ReasonForRequesting: string;
  RequestID: string;
}

// Define the Mongoose schema for the request
const RequestSchema: Schema = new Schema({
  userType: { type: String },
  fullName: { type: String, required: true },
  phoneNumber: { type: String, required: true },
  emailAddress: { type: String, required: true },
  homeAddress: { type: String, required: true },
  medicalCondition: String,
  milkAmount: String,
  BabyCategory: { type: String, required: true },
  ReasonForRequesting: { type: String, required: true },
  RequestID: { type: String, default: () => randomatic('Aa0', 20) }, // Assuming RequestID is autogenerated
});

// Define and export the Mongoose model based on the schema
const RequestModel = mongoose.model<Request>('Request', RequestSchema);

export default RequestModel;
